# Generated by Django 2.1.1 on 2018-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socker_name', models.CharField(max_length=1024)),
                ('socker_id', models.IntegerField()),
                ('competition', models.CharField(max_length=512)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('birth', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('home_filed', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=512)),
                ('start_time', models.TimeField()),
                ('home_club_name', models.CharField(max_length=1024)),
                ('home_club_id', models.IntegerField()),
                ('home_club_score', models.IntegerField()),
                ('guest_club_name', models.CharField(max_length=1024)),
                ('guest_club_id', models.IntegerField()),
                ('guest_club_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socker_name', models.CharField(max_length=1024)),
                ('socker_id', models.IntegerField()),
                ('competition', models.CharField(max_length=512)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=512)),
                ('season', models.CharField(max_length=255)),
                ('club_id', models.IntegerField()),
                ('club_name', models.CharField(max_length=1024)),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Socker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('club_id', models.IntegerField()),
                ('club', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=255)),
                ('birthday', models.TimeField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('message', models.CharField(max_length=1024)),
            ],
        ),
    ]
